[package]
name = "memory-safe-calculator-written-in-a-language-that-is-both-rusty-and-named-after-a-fungus"
version = "0.6.9"
edition = "2021"

[dependencies]
lazy_static = "1.4.0"
colored = "2.0.0"
eval = "0.4.3"
